### ISSUE TITLE
Moved my `.service` files to production, now they can't find node.

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#101]
## This is pretty important as my main production server is down right now

@BytewaveMLP Sorry for the ping,

I managed to implement what we were talking about last night in my testing env, however, when I copied my ``.service`` scripts to my production env, I get the following error:

```sh
Sep 09 18:28:58 Dergun-Town-Public systemd[1]: Started Dergun Town Login Service.
Sep 09 18:28:58 Dergun-Town-Public systemd[3455]: dt-login.service: Changing to the requested working directory failed: No such file or directory
Sep 09 18:28:58 Dergun-Town-Public systemd[3455]: dt-login.service: Failed at step CHDIR spawning /usr/bin/node: No such file or directory
Sep 09 18:28:58 Dergun-Town-Public systemd[1]: dt-login.service: Main process exited, code=exited, status=200/CHDIR
Sep 09 18:28:58 Dergun-Town-Public systemd[1]: dt-login.service: Failed with result 'exit-code'.
```

I'm not sure why it's suddenly not seeing the ``node`` file, that is there if you ``cd`` to bin.

Any ideas? The setup is identical to my testing env.

**Comment by BytewaveMLP** [comment]
It's not that systemd can't find node, it's that it can't find the directory you have set as your WorkingDirectory. That should point at the path to your server installation.

**Comment by UpperCenter** [comment]
I see that now, holy shit what a moron I am,

Thanks for that one! I owe you!

**Comment by BytewaveMLP** [comment]
Don't worry about it, happens to the best of us. 😄
