### ISSUE TITLE
Adding Discord button gives "has no exported member" errors

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#109]
I've updated the files in on my testing environment to include all the modified files with 9f30d98895b44c9c23f5abce58745a12d0b208ba, but I'm running into some issues compiling after adding my link to my ``config.json`` files,

Did I forget to include something?

Output of ``npm run build``

```bash
[19:22:01] Starting 'npm run ts'...

> pony-town@0.53.1-alpha ts /var/www/dergun.town
> tsc --rootDir src/ts --outDir src/scripts --pretty

src/ts/client/game.ts:14:43 - error TS2305: Module '"../common/constants"' has no exported member 'DISCORD_PONY'.

14  OFFLINE_PONY, MAX_SCALE, SUPPORTER_PONY, DISCORD_PONY, HOUR, MIN_SCALE, CAMERA_WIDTH_MIN, CAMERA_WIDTH_MAX,
                                             ~~~~~~~~~~~~

src/ts/client/icons.ts:4:2 - error TS6133: 'faDiscord' is declared but its value is never read.

4  faDiscord,
   ~~~~~~~~~

src/ts/components/app/app.ts:11:97 - error TS2305: Module '"../../client/icons"' has no exported member 'faDiscord'.

11 import { faTwitter, faPatreon, faEnvelope, faCog, faHome, faGamepad, faInfoCircle, faHorseHead, faDiscord } from '../../client/icons';
                                                                                                   ~~~~~~~~~

src/ts/components/shared/discord-pony/discord-pony.ts:4:10 - error TS2305: Module '"../../../common/constants"' has no exported member 'DISCORD_PONY'.

4 import { DISCORD_PONY } from '../../../common/constants';
           ~~~~~~~~~~~~


Found 4 errors.
```

Thanks

EDIT: I added ``faDiscord`` to ``src/ts/client/icons.ts`` to see if that fixed anything.

**Comment by BytewaveMLP** [comment]
Er... hm. Your changes look like they're out of sync with ours, somehow? It seems like you're missing ef316acfe4b4183fa4ddffe30a6c2641adb23f81, which is the commit I added `faDiscord` in.

When did you clone our fork, before or after Aug. 30? Have you run an `npm install` since then?

**Comment by BytewaveMLP** [comment]
How are you merging changes, anyway? I'm not sure how you've managed to get out of sync like this.

**Comment by UpperCenter** [comment]
I cloned the repo ages ago, pretty much straight after the Archive Commit. 

I just kind of stuck the code on the side, thats why I was getting that issue.

**Comment by Tschrock** [comment]
`DISCORD_PONY` was added to  `src/ts/common/constants.ts` in that commit, but it looks like you're missing that: https://github.com/ponydevs/pixel.horse/commit/9f30d98895b44c9c23f5abce58745a12d0b208ba#diff-9c6745b0e2ccf1a56636d90a7b37ad8fR139

**Comment by BytewaveMLP** [comment]
By "stuck the code on the side," what do you mean? Are you manually applying these patches by hand?

**Comment by Stubenhocker1399** [comment]
I can recommend using [git](https://git-scm.com/).

**Comment by UpperCenter** [comment]
> By "stuck the code on the side," what do you mean? Are you manually applying these patches by hand?

Basically _y e a h_

I'm not sure how can I can take my private code repo and merge your changes with it without breaking everything.

**Comment by BytewaveMLP** [comment]
Commit your changes on your own. When you pull from our branch, git will automatically merge our changes into yours (and have you manually do it if it can't safely do it on its own). That's what it's meant to do. :P

**Comment by UpperCenter** [comment]
How does one "pull from our branch" :p

**Comment by BytewaveMLP** [comment]
What I would recommend is making your own repository here, private if you want. Clone our changes, and change the `origin` remote to your own private repository with the following:
```
git remote set-url origin https://github.com/your_user/your_repo.git
```
Then, add an `upstream` remote to our repository:
```
git remote add upstream https://github.com/ponydevs/pixel.horse.git
```
When you want to pull our changes into yours, use `git pull upstream master`. Git will take any changes you've committed, and any changes we've committed, and try to merge them together. If both of us modify the same section of a file, Git will error out due to "conflicts," in which case you'll have to manually go in and merge the changes yourself, then commit the result. Fortunately, [merge conflicts aren't that scary](https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line), especially with an editor like VS Code.

**Comment by BytewaveMLP** [comment]
This may take some work on your end, given the amount of changes you've done so far. But it'll be *far* more maintainable in the future, I assure you. I recommend doing it sooner rather than later, because if you never do it, you'll have more headaches like this.

**Comment by UpperCenter** [comment]
Thanks, I'll look into doing that to keep myself more sane lol.
