### ISSUE TITLE
Add more clovers to an account?

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#122]
I'm doing testing with rewards upon users gathering certain amounts of clovers. In a testing setting, it's quite a grind to get the required amounts,

Can I modify an account's clover count via CLi / Mongo?

Thanks.

**Comment by Tschrock** [comment]
While we love helping people with their questions, I'd like to prevent this issue tracker from becoming a support forum. We have a discord chat at https://chat.pixel.horse where questions like this would fit much better. Thanks!
