### ISSUE TITLE
/settings/settings.json file missing

### ISSUE THREAD

**Issue by Stubenhocker1399** [ponydevs/pixel.horse#22]
When running the server and trying to change server settings via the admin panel this error message pops up.
`ENOENT: no such file or directory, open '/home/chris/pony-town-custom/settings/settings.json'`

Creating an empty json file manually fixes this.

**Comment by blackhole12** [comment]
This seems like a simple "file doesn't exist" issue where the code needs to create the file if it doesn't exist.

**Comment by BytewaveMLP** [comment]
Not yet fixed; errors out with

    Error reading settings file: Error: ENOENT: no such file or directory, open ./settings/settings.json'

`e` is an `Error` object; need to compare its properties, not its own value :p.
