### ISSUE TITLE
Clean up code linting

### ISSUE THREAD

**Issue by blackhole12** [ponydevs/pixel.horse#26]
The linter file used by the project is written from scratch - it should ideally be derived from a standard linter file with minor changes being made to it.

The files also use tabs instead of spaces. Some people have expressed a preference for spaces instead of tabs.

**Comment by LunarMist** [comment]
I tested out using a slightly modified `tslint-config-airbnb` config, and there were over 3K issues...so yeah, no thanks.

The default tslint settings that he used seems rather ok, other than the use of CRLF and tabs. So I made those changes.

If we wish to enforce the more popular linter configs, then we will have to add those on as-needed.
