### ISSUE TITLE
I don't understand, what am I missing?

### ISSUE THREAD

**Issue by LunaSquee** [ponydevs/pixel.horse#48]
I tried to set up my own instance of this fork but for some reason, the web server always 404's at `/assets/scripts/bootstrap.js`.

I did `npm install`, `npm run build` and `npm start`, configured everything, but that file is still missing in production. I had no errors during build.

**Comment by LunaSquee** [comment]
Never mind, my server doesn't have nearly enough memory to build this thing from scratch.

**Comment by BytewaveMLP** [comment]
The build process consumes up to 6GB of memory on a good day, yeah. It's not for the faint of heart. 😬
