### ISSUE TITLE
Server works locally, but accessing it through wan results in loading loop

### ISSUE THREAD

**Issue by PancakeSparkle** [ponydevs/pixel.horse#53]
The server works locally, setting the config to use my domain makes it accessible through WAN, but it's stuck in a never-ending loading loop, I used the config template and edited it to use the domain instead of localhost, it gets to the loading part and then just stops, no errors are reported, is there anything special I need to do with the config to get it working? Server is running on an arch linux server

**Comment by BytewaveMLP** [comment]
Is there any output in your browser's developer console when the game is stuck loading? I had this issue on my dev server before, and it was just a case of missing a config value and getting a CSP error.

**Comment by LunaSquee** [comment]
Build the application again after changing the configuration, usually helps me.

**Comment by BytewaveMLP** [comment]
Also a good point. Some parts of the config are baked into the build instead of loading dynamically.

**Comment by brandons209** [comment]
Alright, so what should the host config option be then? The domain address correct?

**Comment by BytewaveMLP** [comment]
Correct. `host` should be `http(s)://your.domain/`. *Note the trailing `/`*, as it's important for generating the CSP.

Actually, that's technically a bug.

**Comment by PancakeSparkle** [comment]
Wait, what config value were you missing, bytewave?

**Comment by BytewaveMLP** [comment]
I'd forgotten to change `host`, and then forgot the trailing `/`. 😉

**Comment by brandons209** [comment]
Also, for the configuration the server for the games should still point to the localhost correct? With that, it also says you need to use http proxy to run multiple services (i.e the login and game servers) through the same IP. Could you point me in the right direction for doing that?

I am rebuilding it now, hopefully that works.

**Comment by LunaSquee** [comment]
Nginx is your best bet for proxying. And yes, I've found that there is no need to change the other localhosts.

**Comment by BytewaveMLP** [comment]
For the `local` fields, I've just been leaving those as `localhost:8090`, yeah.

When the README mentions HTTP proxying, it means running the tools, gameservers, login server, and admin interface should be set up using a reverse proxy like NGINX. For instance (note: not a complete config):

```nginx
server {
    listen 80;
    # ...

    location / {
        # login server
        proxy_pass http://localhost:8090;
    }

    location /admin {
        # admin panel, separate process
        proxy_pass http://localhost:0891;
    }

    # etc...
}

**Comment by brandons209** [comment]
> For the `local` fields, I've just been leaving those as `localhost:8090`, yeah.
> 
> When the README mentions HTTP proxying, it means running the tools, gameservers, login server, and admin interface should be set up using a reverse proxy like NGINX. For instance (note: not a complete config):
> 
> ```nginx
> server {
>     listen 80;
>     # ...
> 
>     location / {
>         # login server
>         proxy_pass http://localhost:8090;
>     }
> 
>     location /admin {
>         # admin panel, separate process
>         proxy_pass http://localhost:0891;
>     }
> 
>     # etc...
> }
> ```
> 
> If you just want a quick n' dirty setup, however, there's no need for running multiple processes. `npm start` or `node pony-town.js --game --login --admin` will run everything on `:8090` just fine.

Alright great, thank you! I am just trying to get the server running from WAN first, but this helps a lot.

**Comment by BytewaveMLP** [comment]
Happy to help!

For reference, by the way, pixel.horse uses the following NGINX config:

```nginx
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 443;
        ssl on;

        ssl_certificate /etc/letsencrypt/live/pixel.horse/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pixel.horse/privkey.pem;

        server_name pixel.horse www.pixel.horse;

        location / {
            proxy_pass http://127.0.0.1:8090;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
```

**Comment by LunaSquee** [comment]
https://pony.lunasqu.ee uses pretty much the same thing, works great

**Comment by brandons209** [comment]
Alright, so for the port defined in the config, should that stay 8090 and I just use a redirect (either nginx or just a portforward) for 80 - > 8090, or do I specify port 80 in the config? Thank you!

**Comment by LunaSquee** [comment]
I recommend leaving it 8090 in the config and proxying it with nginx.

**Comment by brandons209** [comment]
Sorry for all the questions: where are the build files stored? I'm still a little new to web dev and all of these tools.

**Comment by TheBluekr** [comment]
> ```nginx
>     server {
>         listen 443;
>         ssl on;
> 
>         ssl_certificate /etc/letsencrypt/live/pixel.horse/fullchain.pem;
>         ssl_certificate_key /etc/letsencrypt/live/pixel.horse/privkey.pem;
> 
>         server_name pixel.horse www.pixel.horse;
> 
>         location / {
>             proxy_pass http://127.0.0.1:8090;
>             proxy_http_version 1.1;
>             proxy_set_header Host $http_host;
>             proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection $connection_upgrade;
>         }
>     }
> ```

Does there also happens to be a version for apache?

**Comment by LunaSquee** [comment]
`build` for front end assets and `src/scripts` for server, you don't need to delete these. And no problem, ask away.

**Comment by BytewaveMLP** [comment]
@TheBluekr I haven't used Apache in a while, unfortunately. Something like [this](https://www.happyassassin.net/2018/11/23/reverse-proxying-websockets-with-apache-a-generic-approach-that-works-even-with-firefox/) may help?

**Comment by brandons209** [comment]
Just wanted to say we really appreciate all your help and this fork here! I'm doing some rebuilding currently and I'll let you know how this works out.

**Comment by TheBluekr** [comment]
> @TheBluekr I haven't used Apache in a while, unfortunately. Something like [this](https://www.happyassassin.net/2018/11/23/reverse-proxying-websockets-with-apache-a-generic-approach-that-works-even-with-firefox/) may help?

Will give it a go, thanks regardless.

**Comment by BytewaveMLP** [comment]
> `build` for front end assets and `src/scripts` for server, you don't need to delete these.

Deleting `src/scripts` is actually potentially dangerous, as the build process relies on some of the compiled tool scripts in there to be built before you can... y'know, build. This circular dependency is tracked in #43, however it may require a decent refactor of the project in order to fix.

Again, happy to help @brandons209. Hope things work out well for ya.

**Comment by Stubenhocker1399** [comment]
For a server in dev mode to work over wan you need to modify https://github.com/ponydevs/pixel.horse/blob/3599e91bc01573c2c1348dc89001052bfee2f9d6/views/index.pug#L78-L79 to point to the correct hostname.

**Comment by LunaSquee** [comment]
> Deleting src/scripts is actually potentially dangerous, as the build process relies on some of the compiled tool scripts in there to be built before you can... y'know, build.
I guess so, but the build scripts build all this stuff regardless as far as I can see

**Comment by BytewaveMLP** [comment]
@LunaSquee Not entirely. `src/ts/tools/create-sprites.ts` is never built by anything, as far as I can tell. It relies on content from `src/ts/generated/sprites.ts`... the file it is meant to generate.

This is only really a problem when building the spritesheets, but it still prevents truly clean builds from being possible, as in order to generate `src/ts/generated/sprites.ts` you need `src/ts/generated/sprites.ts` to exist with all the correct types/values.

**Comment by LunaSquee** [comment]
> @LunaSquee Not entirely. `src/ts/tools/create-sprites.ts` is never built by anything, as far as I can tell. It relies on content from `src/ts/generated/sprites.ts`... the file it is meant to generate.
> 
> This is only really a problem when building the spritesheets, but it still prevents truly clean builds from being possible, as in order to generate `src/ts/generated/sprites.ts` you need `src/ts/generated/sprites.ts` to exist with all the correct types/values.

I'm talking explicitly about `src/scripts`, the scripts directory inside of src.

**Comment by LunaSquee** [comment]
> For a server in dev mode to work over wan you need to modify
> 
> https://github.com/ponydevs/pixel.horse/blob/3599e91bc01573c2c1348dc89001052bfee2f9d6/views/index.pug#L78-L79
> 
> to point to the correct hostname.
> Having this not hard coded in would be nice.

I definitely do not recommend running a development server over WAN.

**Comment by brandons209** [comment]
Alright so I rebuilt after changing my host to `host: http://mydomain/` and `port: 8090`. Currently I have port 80 forwarded to the IP address of my server (LAN) port 8090. What happens is that it is trying to load but times out. If I try to access it using its LAN IP directly, I get stuck on a ponytown loading screen saying Loading... From the console its just trying to load the main page. Should I try using the nginx redirect? Maybe just a straight port forward is to blame.

**Comment by LunaSquee** [comment]
I don't understand what you're saying here.. And no you don't need a certificate for http (port 80).

What is timing out? What's your nginx config?

**Comment by BytewaveMLP** [comment]
Port forwarding only works if your server binds to the port you're opening. Pony Town binds to 8090, 
but you're forwarding 80. Even if you change the "local" port in your router, it's not really guaranteed to work. You'll either have to set up nginx or set `host` to `http://your.domain:8090/` and send people to there instead of leaving the port off.

**Comment by brandons209** [comment]
Sorry if I was a bit confusing. I am not using nginx currently, I just want to make sure the server can be access outside before going through and continuing setting up a more permanent server. I am simply forwarding 80 -> 8090 from the router to the server in the LAN. I know I don't need a certificate but I considered it may not connect over wan if there isn't one, not sure on that. 

I will change it to 8090 in both the config and Port forward to try that. Thanks.

**Comment by brandons209** [comment]
Still the same issue, tried logging into http://mydomain:8090/ and it just sits there trying to load the webpage. Seems like the issue is not with the port forward but the configuration of the server itself.

**Comment by BytewaveMLP** [comment]
And again, your `host` parameter is set to *exactly* `http://mydomain:8090/`?

**Comment by brandons209** [comment]
"port": 8090,
        "adminPort": 8091,
        "host": "http://mydomain:8090/",
        "local": "localhost:8090",
        "adminLocal": "localhost:8091",

**Comment by BytewaveMLP** [comment]
Did you rebuild the site after making your last change to `host`?

**Comment by brandons209** [comment]
That has been done as well. I tripled checked the port forward or everything. I am thinking of just starting from a clean project folder and trying again, maybe I messed up somewhere.

**Comment by BytewaveMLP** [comment]
If you have no local modifications, that may help. There are no errors in either the app's log or your browser's console, right?

**Comment by brandons209** [comment]
Correct, The page doesn't even load to actually throw an error, its stuck trying to load the main login page. I am just trying to get the base server running so I will do that now.

**Comment by brandons209** [comment]
Still the same issue occuring. I can't see why I can connect over LAN but not through the port forwarded WAN address.

**Comment by BytewaveMLP** [comment]
Apologies for the late reply.

I wonder... you've tried a non-cached reload, right? Ctrl-Shift-R? Pony Town is a progressive web app, which means it precaches all of its resources and responds with 200 even while it's offline—it just won't load anything else because it can't actually connect to the origin server for API responses. It's possible the WAN connection *is* actually failing, but you haven't noticed because of this.

**Comment by brandons209** [comment]
Yes, I tried different browsers and private mode to make sure. It is definitely not loading. I am going to setup nginx and see if that helps this.

**Comment by PancakeSparkle** [comment]
Blue got the thing working on his server, but somehow it's failing to load game assets

**Comment by BytewaveMLP** [comment]
Are you using our fork, or the main download from PT?

**Comment by TheBluekr** [comment]
Fork

**Comment by BytewaveMLP** [comment]
Did you remember to install git LFS?

**Comment by TheBluekr** [comment]
I did install it.

**Comment by BytewaveMLP** [comment]
Before or after you `git clone`'d? It's important to have it installed before you clone, or the assets won't actually be downloaded.

You can use `git lfs pull` to pull the assets if you installed git LFS after you cloned.

**Comment by TheBluekr** [comment]
I'll have a go at it and report back.

**Comment by TheBluekr** [comment]
Works now, thanks for mentioning it.

**Comment by TheBluekr** [comment]
New issue.
`WebSocket connection to 'wss://example.com/s00/ws' failed: Error during WebSocket handshake: Unexpected response code: 500`
I proxied through based on anything I could find with @PancakeSparkle. The page works fine and everything loads except the websocket.

**Comment by BytewaveMLP** [comment]
What webserver config are you using? Seems that's a response from your web server, unless there's output from the game server console.

**Comment by PancakeSparkle** [comment]
he's using apache, since he couldn't get nginx working, replaced the actual domain name with "domain"
`<VirtualHost *:443>
        ServerName ponytown.domain.name

        ErrorLog /var/log/apache2/error.log
        CustomLog /var/log/apache2/access.log combined

        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/domain.pem
        SSLCertificateKeyFile /etc/apache2/ssl/domain.key

        ProxyPreserveHost On
        ProxyRequests Off

        RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC,OR]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "wss://127.0.0.1:8090/%{REQUEST_URI}" [P,QSA]

        ProxyPass / http://127.0.0.1:8090/
        ProxyPassReverse / http://127.0.0.1:8090/

        ErrorLog /var/log/apache2/ponytown.domain_error.log
        CustomLog /var/log/apache2/ponytown.domain_forwarded.log common_forwarded
        CustomLog /var/log/apache2/ponytown.domain_access.log combined env=!dontlog
        CustomLog /var/log/apache2/ponytown.domain.log combined
</VirtualHost>
`

**Comment by PancakeSparkle** [comment]
So, i saw some ssl errors in the apache logs, fixed those, now i get error 520

**Comment by PancakeSparkle** [comment]
apparently 520 is a Cloudflare error, tomorrow we're going to try with Cloudflare disabled and see what it does, does anyone else have a Cloudflare-protected server?

**Comment by brandons209** [comment]
how do I view logs/error/connection console when the server is running? I am still having an issue.

**Comment by TheBluekr** [comment]
Everything works here too now. For future reference for others I use this.
`	RewriteEngine On
	RewriteCond %{HTTP:Upgrade} =websocket
	RewriteRule /(.*) ws://127.0.0.1:8090/$1 [P,QSA,L]
	RewriteCond %{HTTP:Upgrade} !=websocket
	RewriteRule /(.*) http://127.0.0.1:8090/$1 [P,QSA,L]`
With the local set to "127.0.0.1" and port "8090".

**Comment by LunaSquee** [comment]
Considering it solved, then.
