### ISSUE TITLE
Unable to load any game assets

### ISSUE THREAD

**Issue by Derguns** [ponydevs/pixel.horse#56]
#### Nothing I do seems to solve this one.

I can't for the life of me get the game assets to load - none of them.
I've rebuild my ``config.json`` file 3 times now looking for an issue, but nothing seems to make a difference.
The website loads and any HTML modifications I make all go through correctly.
I've tried to get this working on:
* Debian 10 
* Ubuntu 18.4 
* Windows 2019 Datacenter 
* Windows 10 Pro 

All have this issue, and are high spec machines or VPS systems.  I've tried manually inputting the file paths to images _I know_ are there, such as ``http://ip.address.here:8090/assets/images/test.png`` but all just lead to 404 pages. The backend database was all setup as per the ``readme.md`` file, using the latest pull from this Git.

Totally out of ideas here, any help would be appreciated.

**Comment by BytewaveMLP** [comment]
Have you installed git LFS?

**Comment by Derguns** [comment]
``git lfs pull`` doesn't seem to work for me, I just get thrown an ``git: 'lfs' is not a git command.`` 

I'm using the ``git-full`` instalation too

**Comment by BytewaveMLP** [comment]
It's a separate extension to git; I believe Ubuntu 18.04 includes it in the repos but it isn't installed by default. See [the installation guide](https://github.com/git-lfs/git-lfs/wiki/Installation).
