### ISSUE TITLE
Is it possible to get the gulp dev --sprites fix? 

### ISSUE THREAD

**Issue by Derguns** [ponydevs/pixel.horse#59]
I'm looking to re-generate the sprite sheets in my own version so that I can add in my custom objects, but with the error it means it's impossible to add in custom assets. I saw you guys had a fix already but were waiting to push, and was wondering if it'd be possible to put a +1 for seperating that out and putting it up.

**Comment by BytewaveMLP** [comment]
The sprites should build fine with the current repo, it's just clean builds that are broken.

You do need to create the `/tools/output` directory in your project folder manually, but I believe that's the only issue so far with unclean builds.

**Comment by Derguns** [comment]
Thanks! I managed to get my sheets to compile from your repo. :)
