### ISSUE TITLE
(Question) How to debug infinite loading?

### ISSUE THREAD

**Issue by Derguns** [ponydevs/pixel.horse#75]
I'm working on adding in custom manes to my server, and although I've managed to go through the server and build the spritesheets using --beta with no noted errors, along with adding in the offsets for the accessories and extra items, upon leaving the --beta environment and building normally (again, with no noted errors) the game enters an infinite loading loop. I was wondering if you guys knew how to debug this or if you had experience adding in custom pony assets?

**Comment by Stubenhocker1399** [comment]
Did you get the server properly running initially without any modifications?

**Comment by UpperCenter** [comment]
### This has escalated to way more than that now.

So, we have 2 servers. One is the "public build" where people can actually access the game and play. This server werks all good. We also have a testing server where stuff is yknow... tested. Last night we added some new sprites to the testing server and it stopped working. We're just getting stuck on the initial game loading screen

I've tried a load of different things to fix this, including restoring from an older backup, redownloading all the files and building the server from scratch, and lastly, creating a system level backup of the working public server, and duplicating it. None of these options have made any difference and the game still infinitely loads. 

Also, does _anyone_ know where I can find some logs for this? because I can't seem to find anything that could be helpful. (The game compiles fine so no node errors are reported) 

I'm at a loss again....

**Comment by Stubenhocker1399** [comment]
So is this server not hosted locally and running in development mode?

**Comment by Stubenhocker1399** [comment]
What are your configuration files?

**Comment by UpperCenter** [comment]
No, both servers are remote Linux boxes. What config files do you need? Chrome cache cleared, same error. I think for now I'm going to re-download the latest commit from this repo, and try adding our edits again. Will update.

**Comment by Stubenhocker1399** [comment]
The main config file that I would care about is the `config.json`, mainly the server section and all url related parameters. Make sure not to leak your keys.

Let me get this straight, did the servers both initially run fine _without_ your edits?

Note: By default the development mode  only works via localhost.

**Comment by UpperCenter** [comment]
Both servers ran fine _with_ certain edits, It was only after @Derguns added some new sprites last night that stuff literally stopped loading. We've added custom sprites before last night and they seemed to work fine.

This is my redacted config, I usually use Nginx as a reverse proxy, but I've removed that from the mix for now and I'm just using Node now.

What really gets me is how this was all working fine yesterday, no config edits were made.

```json
{
        "title": "Dergun Town",
        "twitterLink": "https://twitter.com/UpperCenter",
        "contactEmail": "tom@uppercenter.co",
        "port": 8090,
        "adminPort": 8091,
        "host": "ip.address.here/",
        "local": "localhost:8090",
        "adminLocal": "localhost:8091",
        "secret": "",
        "token": "",
        "db": "",
        "oauth": {
                "github": {
                        "clientID": "",
                        "clientSecret": ""
                      },

                "discord": {
                        "clientID": "",
                        "clientSecret": ""
                      },

                "twitter": {
                        "consumerKey": "",
                        "consumerSecret": ""
                      }
                  },

        "assetsPath": "assets-source",
        "servers": [
                {
                        "id": "test",
                        "port": 8090,
                        "path": "/s00/ws",
                        "local": "localhost:8090",
                        "name": "Test server",
                        "desc": "Testing server",
                        "flags": {
                                "test": true,
                                "objects": true
                                  }
                            }
                    ]
}```

Thanks

**Comment by Stubenhocker1399** [comment]
Yeah, that config looks fine to me, you might just want to keep unique ports between the login and gameservers.

Did you try out building your changes locally on a dev server first? Or copying your server files and running those in dev mode?

**Comment by Stubenhocker1399** [comment]
I just noticed you referred to building sprites with `--beta` in your first comment. This is not correct, you build them with `--sprites`.

**Comment by Derguns** [comment]
We're building the beta environment and then using gulp dev --sprites once confirming that the environment can be built. It did build both the spritesheets and sprite files with no errors from gulp dev --sprites, and I do have the sheets with the mane assets. However, once this was completed and the sheets moved into the assets/images folder, the game infinite loaded after doing a normal npm build.

**Comment by Stubenhocker1399** [comment]
Building the beta environment and then running `gulp dev --sprites` would replace the just build beta build, as far as I am aware.

Are there no errors at all in your browsers developer tools? Check the console & network tab.
Try checking for errors with both Firefox and Chrome.

**Comment by Stubenhocker1399** [comment]
Ah, I figured it out. your 
```
"host": "ip.address.here/",
```
is missing the `http://` or `https://`.

This generates a Content Security Policy otherwise in release/beta mode while working fine in dev mode.

**Comment by Derguns** [comment]
No errors in our console / network, and our host config IP for the broken server is actually a website URL with the http:// .

**Comment by Stubenhocker1399** [comment]
Please try running a local dev server with your changes.

**Comment by UpperCenter** [comment]
Welp. Long story short I cloned the original PT files from their Mega link. Redid everything in a production environment and all my files and changes are there now. No idea what was causing the issue. Marking this as closed I guess? Thanks for everyone's input!

**Comment by Stubenhocker1399** [comment]
Please mark this as closed.
