### ISSUE TITLE
Nginx reverse proxy IP issues.

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#79]
Just a quick question to keep my logs clear.

I'm using Nginx as a reverse proxy for my production environment. Several users were reporting issues connecting to the actual game server after logging out. I was told that adding: 
```json
"proxy": true,
``` 

To my ``config.json`` would help, and it seems to have fixed the issue, however It's flooding my global logs with this:

```sh
pony-town > [Sep 06 21:43:55] [warn] Invalid IP ["users.ip.here"] (originUtils.ts:24)
```

Anyone know how I could fix this minor error?

---

Additionally, does anyone know the files path for the ``.ts`` or ``.pug`` files associated with the index page? I want to add some elements but can't find the sauce files anywhere. Thanks!

**Comment by BytewaveMLP** [comment]
It looks like the `getOrigin` and `getOriginFromHTTP` functions (what's throwing the error here) is specifically written for Cloudflare. See:

```ts
export function getOriginFromHTTP(req: { headers: any; }): IOriginInfo {
	const ip = getIP(req) || '0.0.0.0';
	const ipcountry = (ip === '127.0.0.1' || ip === '::ffff:127.0.0.1' || ip === '::1') ? 'LOCAL' : '';
	const country = ipcountry || req.headers['cf-ipcountry'] || '??';
	return { ip, country, last: new Date() };
}

export function getOrigin(req: Request): IOriginInfo {
	const origin = getOriginFromHTTP(req);

	if (origin.country === '??' && config.proxy) {
		logger.warn('Invalid IP', JSON.stringify(req.ips));
		//create(null, null, null).danger('Invalid IP', JSON.stringify(req.ips));
	}

	return origin;
}
```

In this case, you're getting that error because you aren't running your instance behind Cloudflare (or you have IP geolocation turned off), so the `CF-IPCountry` header is never being set. If you want to get rid of this error and don't want to set up Cloudflare, just comment out the `logger.warn` call.

Later on, we could look into fetching IP geolocation data ourselves, but usually those APIs aren't free.

**Comment by BytewaveMLP** [comment]
Also, re: your second question:

It depends on what you want to change. The app is very component-driven, and any one page could actually be several different templates with separate controllers. The *main* template is `views/index.pug`, and it has no controller; it's compiled by `src/ts/server/routes/index.ts`.

**Comment by UpperCenter** [comment]
> It looks like the `getOrigin` and `getOriginFromHTTP` functions (what's throwing the error here) is specifically written for Cloudflare. See:
> 
> ```ts
> export function getOriginFromHTTP(req: { headers: any; }): IOriginInfo {
> 	const ip = getIP(req) || '0.0.0.0';
> 	const ipcountry = (ip === '127.0.0.1' || ip === '::ffff:127.0.0.1' || ip === '::1') ? 'LOCAL' : '';
> 	const country = ipcountry || req.headers['cf-ipcountry'] || '??';
> 	return { ip, country, last: new Date() };
> }
> 
> export function getOrigin(req: Request): IOriginInfo {
> 	const origin = getOriginFromHTTP(req);
> 
> 	if (origin.country === '??' && config.proxy) {
> 		logger.warn('Invalid IP', JSON.stringify(req.ips));
> 		//create(null, null, null).danger('Invalid IP', JSON.stringify(req.ips));
> 	}
> 
> 	return origin;
> }
> ```
> 
> In this case, you're getting that error because you aren't running your instance behind Cloudflare (or you have IP geolocation turned off), so the `CF-IPCountry` header is never being set. If you want to get rid of this error and don't want to set up Cloudflare, just comment out the `logger.warn` call.
> 
> Later on, we could look into fetching IP geolocation data ourselves, but usually those APIs aren't free.

Thanks for that reply, I know some places do Geolocation API's but if they're free they have a strict limit on how many requests you can pull.

**Comment by BytewaveMLP** [comment]
Unfortunately, yeah. Either it's free and limited, or paid and possibly still limited.

**Comment by UpperCenter** [comment]
> Unfortunately, yeah. Either it's free and limited, or paid and possibly still limited.

Not sure I'd like to use Cloudflare either tbh. Maybe Fast.ly or some other provider.

**Comment by BytewaveMLP** [comment]
Your server, your choice. `CF-Connecting-IP` and `CF-IPCountry` should be the only Cloudflare-specific headers Pony Town looks for. I can look into equivalents from different providers to make pixel.horse more portable, or at the very least make sure that `config.proxy` isn't immediately assumed to mean "behind Cloudflare" and instead "behind *any* proxy."

**Comment by UpperCenter** [comment]
I'm not seeing any "text" that I can edit in order to change the content of the index page in any of the files / folders you mentioned.  Ideally I'd like to add some HTML underneath the main logo. I can do this using the inspect element feature of Firefox, not sure what files I should be looking for though. 

What am I missing?

**Comment by BytewaveMLP** [comment]
You probably want to edit `src/ts/components/app/home/home.pug` then. That's where the logo is.

**Comment by UpperCenter** [comment]
Oof it was looking right at me. Thanks for that one ^^
