### ISSUE TITLE
Building sprites failed

### ISSUE THREAD

**Issue by LunaSquee** [ponydevs/pixel.horse#82]
After #76, I get the following error when building sprites:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.<anonymous> (/home/evert/Projects/pixel.horse/src/ts/tools/create-sprites.ts:42:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by BytewaveMLP** [comment]
That's a new one... `node -v`?

**Comment by LunaSquee** [comment]
`v10.16.3`

**Comment by LunaSquee** [comment]
Never mind, it seems that my config has somehow lost the `	"assetsPath": "assets-source",` entry..

**Comment by BytewaveMLP** [comment]
Yeah, I was gonna say, looks like that's not something I did. :P 

There *are* a few errors with clean builds still... but I believe `npm run build-sprites` should work fine clean, at least.

**Comment by LunaSquee** [comment]
`  "assetsPath": "<path_to_graphics_assets>", // optional, for asset generation`
Remove the "optional" part from README.md or set a default value for it in `create-sprites.ts`

**Comment by LunaSquee** [comment]
Now i keep getting a 404 at `/assets/images/pony.png` even though they generated and i copied them to the assets/images dir.. weird

**Comment by BytewaveMLP** [comment]
Weird indeed. Any errors during your build, or on your server's end?

Also, for the config: I really should just merge the template with the README's version. Why they're so different I'm not sure.

**Comment by LunaSquee** [comment]
![](https://i.lunasqu.ee/Screenshot_19-09-07-08:44:56.png)

**Comment by LunaSquee** [comment]
Don't think there were any errors during build

**Comment by BytewaveMLP** [comment]
Is this a dev build, or a normal build? It looks like the revision hashing isn't being applied...?

**Comment by LunaSquee** [comment]
It is a normal build. I ran `npm run build-sprites` and deployed it

**Comment by LunaSquee** [comment]
There are not `pony` files in `build/assets/images`, just `$PROJECT_ROOT/assets/images`

**Comment by BytewaveMLP** [comment]
Something seems to have happened to your `assetsCopy`  task. You're sure there were no errors during your build? Some errors may not cause the process to exit.

**Comment by LunaSquee** [comment]
```
[08:49:06] Starting 'assetsCopy'...
[08:49:19] gulp-imagemin: Minified 7 images (saved 36.6 kB - 38.3%)
[08:49:19] Finished 'assetsCopy' after 13 s
```

**Comment by BytewaveMLP** [comment]
Is that from a new build, or your previous one?

**Comment by LunaSquee** [comment]
New one. Maybe it will work this time, then.

**Comment by LunaSquee** [comment]
I did not notice any errors pop up before and I can't scroll up far enough due to the massive ts compilation logs xD

**Comment by LunaSquee** [comment]
I guess you have to build it twice now for the pony sheets to be properly revision hashed

**Comment by BytewaveMLP** [comment]
Ah. I may have messed up the order for tasks to run during a `build-sprites`. I can get it working when reordering them, but a fully clean build will make TS complain—even if it complies the content. :P

**Comment by LunaSquee** [comment]
Yeah now everything is OK.

**Comment by LunaSquee** [comment]
I really should've tested the PR, hmu next time for a review, I can do clean deployments of new versions since I don't have a player base who would get upset about downtime xD

**Comment by BytewaveMLP** [comment]
I mean, I had tested it, just hadn't realized `pony*.png` were output to `/assets` before being rev'd. Missed that during my testing.

I can now get reproduceable clean builds, even if `tsc` complains. So I'm doing something right. I'll commit my fix.

**Comment by LunaSquee** [comment]
Alright, thank you
