### ISSUE TITLE
(Question) Adding multiple gameservers

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#84]
### Easy questions here,

Just going to throw down some simple questions that are too simple / small to make separate threads about.

First, I'd like to add a few more gameservers to my production environment. 
I realise this is probably just copying my regular server settings in ``config.json``, but I'm not sure what path to change to. The default path I'm using for my one server is ``"path": "/s00/ws",``. I realise I can't just copy the settings, but does anyone have a working example they'd like to share?

Secondly, Setting country flags doesn't seem to have any effect. I use several that I'm sure work like ``"flag": "GB",`` and ``"flag": "RU",`` but they don't seem to work, even after a full rebuild. Am I using the wrong codes?

Finally, how can I enable the Patreon features of PT? I see the code is commented out in the "About" page, but how can I specify my own API key for account linking, and where can I add a link to my Patreon page?

I know I'm asking a lot recently, Thanks for bearing with me! ^^

EDIT: I should add I'm trying to add a dedicated PG server and RU server. Is there a way to ensure that users with Russian characters in their name can only use the RU server, or does that require manuel moderation?

**Comment by Stubenhocker1399** [comment]
Regarding the patreon features, please contact Chira, the lead of PT, first.

**Comment by UpperCenter** [comment]
Oh, I didn't think it would be an issue to use the code for commercial purposes, as stated in the licence file:
```
Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.
```

Not even sure how I could contact Chira?

**Comment by Stubenhocker1399** [comment]
The code, yes, but did you see the licenses for the art and music?
See [LICENSE_ART.txt](https://github.com/ponydevs/pixel.horse/blob/master/LICENSE_ART.txt) and [LICENSE_MUSIC.txt](https://github.com/ponydevs/pixel.horse/blob/master/LICENSE_MUSIC.txt).

In our Discord (https://chat.pixel.horse) she requested to be contacted first to clear things up properly.  
I'd say contact her either via Discord or the PT email address.

**Comment by BytewaveMLP** [comment]
From my experiments, multiple game servers require multiple ports. Each server needs its own port, otherwise they'll all appear the same to the game's status API, and therefore only one will work.

For a multi-server setup, I'd recommend a multi-process setup as well, so each can be controlled independently. Each game server just needs to be launched with `--game:ID`.

The only big problem with this is getting it to work correctly on the internet. The separate ports are only used internally—PT seems to still expect the websocket endpoints to all respond from the same port as the login server. So, you'll probably have to set up nginx in front of the site, and add location blocks for every `.../ws` path that uses the correct port for its `proxy_pass` directive.

**Comment by UpperCenter** [comment]
> From my experiments, multiple game servers require multiple ports. Each server needs its own port, otherwise they'll all appear the same to the game's status API, and therefore only one will work.
> 
> For a multi-server setup, I'd recommend a multi-process setup as well, so each can be controlled independently. Each game server just needs to be launched with `--game:ID`.
> 
> The only big problem with this is getting it to work correctly on the internet. The separate ports are only used internally—PT seems to still expect the websocket endpoints to all respond from the same port as the login server. So, you'll probably have to set up nginx in front of the site, and add location blocks for every `.../ws` path that uses the correct port for its `proxy_pass` directive.

Got it, thanks for that. I'll probably reply here when it eventually doesn't work haha.

I'm using ``pm2`` node package to manage game sessions at the moment. It's basically just launching the game using ``node pony-town.js -- --login --admin --game --tools`` I'm not sure what a RU server startup command would look like. 
Is it literally just ``node pony-town.js -- --login --admin --game:12 --tools`` for an ID of 12? How does PT know that the ID of 12 is associated with the RU server for example?

**Comment by BytewaveMLP** [comment]
The IDs are specified in your config; each server object has an `id` key. Just make sure those are unique, they can be any value you like.

Also, for separate processes, you'll want to keep your login/admin server a separate process as well. On the pixel.horse instance, I run separate login, admin, and game server processes, using the following systemd units:

`pixelhorse-admin.service`
```ini
[Unit]
Description=pixel.horse - admin

[Service]
Type=simple
User=pixelhorse
Group=pixelhorse
WorkingDirectory=/home/pixelhorse/pixel.horse
ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --admin --standaloneadmin

[Install]
WantedBy=multi-user.target
RequiredBy=pixelhorse-login.service
```

`pixelhorse-game@.service`
```ini
[Unit]
Description=pixel.horse - game "%I"

[Service]
Type=simple
User=pixelhorse
Group=pixelhorse
WorkingDirectory=/home/pixelhorse/pixel.horse
ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --game %i

[Install]
WantedBy=multi-user.target
Requires=pixelhorse-login.service
Requires=pixelhorse-admin.service
```

`pixelhorse-login.service`
```ini
[Unit]
Description=pixel.horse - login

[Service]
Type=simple
User=pixelhorse
Group=pixelhorse
WorkingDirectory=/home/pixelhorse/pixel.horse
ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --login

[Install]
WantedBy=multi-user.target
```

They aren't perfect, but fwiw, they work. The `pixelhorse-game@.service` file specifically allows me to pass in any ID I want after the `@`, and it'll spawn the appropriate game process as defined by the config.

We also use this nginx config to make sure the traffic all gets routed to the right places:
```nginx
server {
	listen 443;
	ssl on;

	ssl_certificate /etc/letsencrypt/live/pixel.horse/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/pixel.horse/privkey.pem;

	server_name pixel.horse;

	location /admin {
		proxy_pass http://127.0.0.1:8091;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}

	location /srv/18/ws {
		proxy_pass http://127.0.0.1:8092;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}

	location /srv/pg13/ws {
		proxy_pass http://127.0.0.1:8093;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}

	location /srv/pg/ws {
		proxy_pass http://127.0.0.1:8094;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}

	location / {
		proxy_pass http://127.0.0.1:8090;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}
}
```

An important note about this setup is to make sure your `local` and `adminLocal` config fields are all set correctly. Each one needs to match the port of the application it refers to, otherwise internal APIs will break. You won't need to forward these other ports unless you're running these separate applications on separate machines, though; all your traffic should go through your nginx instance which will handle all the reverse proxy nonsense.

**Comment by UpperCenter** [comment]
> The IDs are specified in your config; each server object has an `id` key. Just make sure those are unique, they can be any value you like.
> 
> Also, for separate processes, you'll want to keep your login/admin server a separate process as well. On the pixel.horse instance, I run separate login, admin, and game server processes, using the following systemd units:
> 
> `pixelhorse-admin.service`
> 
> ```ini
> [Unit]
> Description=pixel.horse - admin
> 
> [Service]
> Type=simple
> User=pixelhorse
> Group=pixelhorse
> WorkingDirectory=/home/pixelhorse/pixel.horse
> ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --admin --standaloneadmin
> 
> [Install]
> WantedBy=multi-user.target
> RequiredBy=pixelhorse-login.service
> ```
> 
> `pixelhorse-game@.service`
> 
> ```ini
> [Unit]
> Description=pixel.horse - game "%I"
> 
> [Service]
> Type=simple
> User=pixelhorse
> Group=pixelhorse
> WorkingDirectory=/home/pixelhorse/pixel.horse
> ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --game %i
> 
> [Install]
> WantedBy=multi-user.target
> Requires=pixelhorse-login.service
> Requires=pixelhorse-admin.service
> ```
> 
> `pixelhorse-login.service`
> 
> ```ini
> [Unit]
> Description=pixel.horse - login
> 
> [Service]
> Type=simple
> User=pixelhorse
> Group=pixelhorse
> WorkingDirectory=/home/pixelhorse/pixel.horse
> ExecStart=/usr/bin/node /home/pixelhorse/pixel.horse/pony-town.js --login
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> They aren't perfect, but fwiw, they work. The `pixelhorse-game@.service` file specifically allows me to pass in any ID I want after the `@`, and it'll spawn the appropriate game process as defined by the config.
> 
> We also use this nginx config to make sure the traffic all gets routed to the right places:
> 
> ```nginx
> server {
> 	listen 443;
> 	ssl on;
> 
> 	ssl_certificate /etc/letsencrypt/live/pixel.horse/fullchain.pem;
> 	ssl_certificate_key /etc/letsencrypt/live/pixel.horse/privkey.pem;
> 
> 	server_name pixel.horse;
> 
> 	location /admin {
> 		proxy_pass http://127.0.0.1:8091;
> 		proxy_http_version 1.1;
> 		proxy_set_header Host $http_host;
> 		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> 
> 	location /srv/18/ws {
> 		proxy_pass http://127.0.0.1:8092;
> 		proxy_http_version 1.1;
> 		proxy_set_header Host $http_host;
> 		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> 
> 	location /srv/pg13/ws {
> 		proxy_pass http://127.0.0.1:8093;
> 		proxy_http_version 1.1;
> 		proxy_set_header Host $http_host;
> 		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> 
> 	location /srv/pg/ws {
> 		proxy_pass http://127.0.0.1:8094;
> 		proxy_http_version 1.1;
> 		proxy_set_header Host $http_host;
> 		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> 
> 	location / {
> 		proxy_pass http://127.0.0.1:8090;
> 		proxy_http_version 1.1;
> 		proxy_set_header Host $http_host;
> 		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> }
> ```
> 
> An important note about this setup is to make sure your `local` and `adminLocal` config fields are all set correctly. Each one needs to match the port of the application it refers to, otherwise internal APIs will break. You won't need to forward these other ports unless you're running these separate applications on separate machines, though; all your traffic should go through your nginx instance which will handle all the reverse proxy nonsense.

Wow thanks for all that, super helpful.

Would you be able to show the ``servers`` section of your ``config.json``?

Thanks!

**Comment by BytewaveMLP** [comment]
Was going to share that, but it slipped my mind. Sorry about that!

```json
{
	"port": 8090,
	"adminPort": 8091,
	"host": "https://pixel.horse/",
	"local": "localhost:8090",
	"adminLocal": "localhost:8091",
	"proxy": "127.0.0.1",
	"servers": [
		{
			"id": "18+",
			"port": 8092,
			"path": "/srv/18/ws",
			"local": "localhost:8092",
			"name": "18+",
			"desc": "Adults-only 18+ server. Adult content permitted.",
			"alert": "18+"
		},
		{
			"id": "pg13",
			"port": 8093,
			"path": "/srv/pg13/ws",
			"local": "localhost:8093",
			"name": "PG-13",
			"desc": "No adult content/sexual themes. Swearing is permitted."
		},
		{
			"id": "pg",
			"port": 8094,
			"path": "/srv/pg/ws",
			"local": "localhost:8094",
			"name": "PG",
			"desc": "No swearing or adult content."
		}
	]
}
```

**Comment by UpperCenter** [comment]
@BytewaveMLP 
Well, I've managed to setup my extra servers and create the ``systemctl`` services to launch the individual game components. When I run the services, I can see that regardless of what server I'm trying to start, they're all using the same port, so on the website, all my servers show up as offline.

You mentioned something about this kind of issue above, with the ports and NGINX config, however the PT ``config.json`` and ``nginx.conf`` files both use the same ports, so I'm unsure as to why the status API is listing the server as "offline", or why the services seem to be starting on the same ports.

Here is a redacted copy of my PT ``config.json`` file:

```json
{
   "port":8090,
   "adminPort":8091,
   "host":"example.com",
   "local":"localhost:8090",
   "adminLocal":"localhost:8091",


   "oauth":{
   },
   "assetsPath":"assets-source",
   "servers":[
      {
         "id":"main",
         "port":8092,
         "path":"/18/ws",
         "local":"localhost:8092",
         "name":"18+ Main Testing Server",
         "desc":"Welcome to the main server of Dergun.town!",
         "flag":"EN",
         "alert":"18+",
         "flags":{
            "test":true,
            "editor":true,
            "objects":true
         }
      },
      {
         "id":"pg13",
         "port":8093,
         "path":"/pg13/ws",
         "local":"localhost:8093",
         "name":"PG 13 Server",
         "desc":"Welcome to the PG 13 Dergun Town server!",
         "flag":"EN"
      },
      {
         "id":"ru",
         "port":8094,
         "path":"/ru/ws",
         "local":"localhost:8094",
         "name":"18+ Russian Server",
         "desc":"Welcome to the Russian server of Dergun.town!",
         "flag":"RU",
         "alert":"18+"
      }
   ]
}
```

The server I was testing this out with was the Russian server, so I've added my ``dt-game-ru.service`` file below:

```
[Unit]
Description=Dergun Town Russian Server

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/var/www/dergun.town
ExecStart=/usr/bin/node /var/www/dergun.town/pony-town.js --game:ru

[Install]
WantedBy=multi-user.target
Requires=dt-login.service
Requires=dt-admin.service
```

It's basically your same config, modified for my setup.

The output log of that service is below:

```
● dt-game-ru.service - Dergun Town Russian Server
   Loaded: loaded (/etc/systemd/system/dt-game-ru.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-09-08 16:31:52 UTC; 16min ago
 Main PID: 11844 (node)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/dt-game-ru.service
           └─11844 /usr/bin/node /var/www/dergun.town/pony-town.js --game:ru

Sep 08 16:31:52 Dergun-Town-Testing systemd[1]: /etc/systemd/system/dt-game-ru.service:13: Unknown lvalue 'Requires' in section 'Install'
Sep 08 16:31:52 Dergun-Town-Testing systemd[1]: /etc/systemd/system/dt-game-ru.service:14: Unknown lvalue 'Requires' in section 'Install'
Sep 08 16:31:52 Dergun-Town-Testing systemd[1]: Started Dergun Town Russian Server.
Sep 08 16:31:54 Dergun-Town-Testing node[11844]: [Sep 08 16:31:54] [info] Listening on port 8092 (production) (server.ts:418)
```
As you can see its using the wrong port there.
Finally, here's the NGINX block specific to the Russian server:

```
	location /srv/ru/ws {
		proxy_pass http://127.0.0.1:8094;
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}
```

Not sure what I'm missing here but it has to be painfully obvious :p

**Comment by BytewaveMLP** [comment]
Your `path` points to `/ru/ws`, but your nginx config points to `/srv/ru/ws`.

Also, what's in your `dt-login.service`?

**Comment by UpperCenter** [comment]
I set the path to ``/ru/ws`` on both with no change. I don't _actually_ know what path I should be using though.

As for my login service:
```
[Unit]
Description=Dergun Town Login Service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/var/www/dergun.town
ExecStart=/usr/bin/node /var/www/dergun.town/pony-town.js --login

[Install]
WantedBy=multi-user.target
```

That's all thats in there.

EDIT: I realise it's terrible practice to run all this as ``root``, but this is just my testing env so I'm not too worried.

**Comment by BytewaveMLP** [comment]
I don't see anything *immediately* out of the ordinary there.  Your config looks comparable to our own, and values match up like they should.

Just as a minor curiosity... `ping localhost` **does** resolve to `127.0.0.1` on your system, right? It *should*, but there are some instances where `/etc/hosts` doesn't actually contain the entry!

**Comment by UpperCenter** [comment]
Seems all good on that front too. Is there a way I can check to make sure I'm using the correct path for my ``ws`` entries?
```
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.046 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.040 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.051 ms
^C
--- localhost ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4072ms
rtt min/avg/max/mdev = 0.021/0.038/0.051/0.011 ms
```

**Comment by BytewaveMLP** [comment]
The "correct path" is determined by those entries. The app creates those routes based on the values you provide.

The servers showing as offline wouldn't be a result of the websockets. It would be the internal API failing to query the different game servers.

What does `sudo netstat -plnt` output?

**Comment by UpperCenter** [comment]
Nothing else is listening on those ports. Oddly enough, it _looks_ like the node servers are listening on the correct ports.
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:0000        0.0.0.0:*               LISTEN      931/mongod          
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1369/nginx: master  
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      717/systemd-resolve 
tcp        0      0 0.0.0.0:000000      0.0.0.0:*               LISTEN      946/sshd            
tcp6       0      0 :::8090                 :::*                    LISTEN      1697/node           
tcp6       0      0 :::8091                 :::*                    LISTEN      1684/node           
tcp6       0      0 :::8092                 :::*                    LISTEN      1689/node           
tcp6       0      0 :::                  :::*                    LISTEN      946/sshd            
```

**Comment by BytewaveMLP** [comment]
I'm only seeing your `main` server running there, port 8092. Is that meant to be running? If so, is the systemd unit laid out the same as the `ru` server's? Does it show as online in game?

**Comment by UpperCenter** [comment]
To get that output, I ran ``systemctl start dt-admin.service dt-game-ru.service dt-login.service``

I'll link the contents of those services, and their corresponding NGINX entries below:

Admin:
```
[Unit]
Description=Dergun Town Admin Service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/var/www/dergun.town
ExecStart=/usr/bin/node /var/www/dergun.town/pony-town.js --admin --standaloneadmin

[Install]
WantedBy=multi-user.target
RequiredBy=dt-login.service
```

Admin Nginx entry:

```
        location /admin {
                proxy_pass http://127.0.0.1:8091;
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
```
RU Gameserver:

```
[Unit]
Description=Dergun Town Russian Server

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/var/www/dergun.town
ExecStart=/usr/bin/node /var/www/dergun.town/pony-town.js --game:ru

[Install]
WantedBy=multi-user.target
Requires=dt-login.service
Requires=dt-admin.service
```

Nginx Entry:

```
        location /ru/ws {
                proxy_pass http://127.0.0.1:8094;
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
```

Login Service:

```
[Unit]
Description=Dergun Town Login Service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/var/www/dergun.town
ExecStart=/usr/bin/node /var/www/dergun.town/pony-town.js --login

[Install]
WantedBy=multi-user.target
```

Nginx Entry

```
        location / {
                proxy_pass http://127.0.0.1:8090;
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-For $http_cf_connecting_ip;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
```

Weirdly, If I start up my Main server instead of my RU one, that uses ``"port":8092`` and ``"local":"localhost:8092",`` I'm told that the port is already in use.

I'm not sure what I've done here lol.

**Comment by BytewaveMLP** [comment]
Do you somehow have a process running in the background that isn't controlled by a unit? Check `htop` with all your units stopped, maybe there's a lingering process?

**Comment by UpperCenter** [comment]
Nothing. Just Nginx' process running. I did a reboot to see if that helped with anything. No luck.

**Comment by UpperCenter** [comment]
The admin and login servers seem to both be working fine, it's just the game ones that don't want to play.

**Comment by BytewaveMLP** [comment]
... you know, I think I found the issue.

It's `--game ID`, not `--game:ID`.

**Comment by UpperCenter** [comment]
> ... you know, I think I found the issue.
> 
> It's `--game ID`, not `--game:ID`. My bad. :/

Hahaha yeah that fixed it, It's all working now :p
Thanks for your help and everything though!
